<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Vestigium.Themes.Controls</RootNamespace>
    <AssemblyName>Vestigium.Themes.Controls</AssemblyName>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vestigium.Themes\Vestigium.Themes.csproj" />
  </ItemGroup>
</Project>
