namespace Vestigium.Themes;

/// <summary>
/// Stable resource-key contract. Every theme package must provide these keys.
/// </summary>
public static class ThemeResourceKeys
{
    public const string ThemeId = "Vestigium.Theme.Id";
    public const string ThemeDisplayName = "Vestigium.Theme.DisplayName";
    public const string ThemeDescription = "Vestigium.Theme.Description";
    public const string ThemeBase = "Vestigium.Theme.Base";
    public const string ThemeIsDark = "Vestigium.Theme.IsDark";
    public const string ThemeVersion = "Vestigium.Theme.Version";
    public const string ThemeShowcase = "Vestigium.Theme.Showcase";

    public const string ContractVersion = "1.0";

    public static readonly IReadOnlyList<string> RequiredMetadata =
    [
        ThemeId, ThemeDisplayName, ThemeBase, ThemeIsDark, ThemeVersion, ThemeShowcase
    ];

    public static readonly IReadOnlyList<string> RequiredColors =
    [
        "Vestigium.Colors.Surface.Window",
        "Vestigium.Colors.Surface.Layer",
        "Vestigium.Colors.Surface.Card",
        "Vestigium.Colors.Surface.Sunken",
        "Vestigium.Colors.Surface.Chrome",
        "Vestigium.Colors.Surface.Sidebar",
        "Vestigium.Colors.Surface.StatusBar",
        "Vestigium.Colors.Surface.Header",
        "Vestigium.Colors.Surface.Hover",
        "Vestigium.Colors.Surface.Disabled",
        "Vestigium.Colors.Control.Fill",
        "Vestigium.Colors.Control.FillHover",
        "Vestigium.Colors.Control.FillPressed",
        "Vestigium.Colors.Control.FillDisabled",
        "Vestigium.Colors.Control.FillInput",
        "Vestigium.Colors.Text.Primary",
        "Vestigium.Colors.Text.Secondary",
        "Vestigium.Colors.Text.Tertiary",
        "Vestigium.Colors.Text.Disabled",
        "Vestigium.Colors.Text.Inverse",
        "Vestigium.Colors.Text.Heading",
        "Vestigium.Colors.Text.OnSubtle",
        "Vestigium.Colors.Text.Inactive",
        "Vestigium.Colors.Text.Code",
        "Vestigium.Colors.Text.Link",
        "Vestigium.Colors.Accent.Primary",
        "Vestigium.Colors.Accent.Hover",
        "Vestigium.Colors.Accent.Pressed",
        "Vestigium.Colors.Accent.Subtle",
        "Vestigium.Colors.Accent.Softer",
        "Vestigium.Colors.Selection.Fill",
        "Vestigium.Colors.Selection.FillInactive",
        "Vestigium.Colors.Selection.Text",
        "Vestigium.Colors.Selection.Highlight",
        "Vestigium.Colors.Selection.CellFocus",
        "Vestigium.Colors.Stroke.Default",
        "Vestigium.Colors.Stroke.Subtle",
        "Vestigium.Colors.Stroke.Strong",
        "Vestigium.Colors.Stroke.Focus",
        "Vestigium.Colors.Stroke.Input",
        "Vestigium.Colors.Stroke.Disabled",
        "Vestigium.Colors.Status.Success",
        "Vestigium.Colors.Status.SuccessHover",
        "Vestigium.Colors.Status.SuccessPressed",
        "Vestigium.Colors.Status.SuccessFill",
        "Vestigium.Colors.Status.Warning",
        "Vestigium.Colors.Status.WarningHover",
        "Vestigium.Colors.Status.WarningPressed",
        "Vestigium.Colors.Status.WarningFill",
        "Vestigium.Colors.Status.Error",
        "Vestigium.Colors.Status.ErrorHover",
        "Vestigium.Colors.Status.ErrorPressed",
        "Vestigium.Colors.Status.ErrorFill",
        "Vestigium.Colors.Status.Info",
        "Vestigium.Colors.Status.InfoFill",
        "Vestigium.Colors.Status.Neutral",
        "Vestigium.Colors.Status.NeutralFill",
        "Vestigium.Colors.Grid.Line",
        "Vestigium.Colors.Grid.AlternateRow",
        "Vestigium.Colors.Grid.Header",
        "Vestigium.Colors.Grid.RowHover",
        "Vestigium.Colors.Scroll.Thumb",
        "Vestigium.Colors.Scroll.ThumbHover",
        "Vestigium.Colors.Scroll.ThumbDrag",
        "Vestigium.Colors.Scroll.Track",
        "Vestigium.Colors.Shadow",
        "Vestigium.Colors.Terminal.Background",
        "Vestigium.Colors.Terminal.Foreground",
        "Vestigium.Colors.Terminal.Border",
        "Vestigium.Colors.Terminal.BackgroundDisabled",
        "Vestigium.Colors.Terminal.Comment",
        "Vestigium.Colors.Terminal.Keyword",
        "Vestigium.Colors.Terminal.String",
        "Vestigium.Colors.Terminal.Number",
        "Vestigium.Colors.Terminal.Error",
        "Vestigium.Colors.Terminal.Cursor",
        "Vestigium.Colors.Series.1",
        "Vestigium.Colors.Series.2",
        "Vestigium.Colors.Series.3",
        "Vestigium.Colors.Series.4",
        "Vestigium.Colors.Series.5",
        "Vestigium.Colors.Series.6",
    ];

    public static readonly IReadOnlyList<string> RequiredBrushes =
    [
        "Vestigium.Brushes.Surface.Window",
        "Vestigium.Brushes.Surface.Layer",
        "Vestigium.Brushes.Surface.Card",
        "Vestigium.Brushes.Surface.Sunken",
        "Vestigium.Brushes.Surface.Chrome",
        "Vestigium.Brushes.Surface.Sidebar",
        "Vestigium.Brushes.Surface.StatusBar",
        "Vestigium.Brushes.Surface.Header",
        "Vestigium.Brushes.Surface.Hover",
        "Vestigium.Brushes.Surface.Disabled",
        "Vestigium.Brushes.Control.Fill",
        "Vestigium.Brushes.Control.FillHover",
        "Vestigium.Brushes.Control.FillPressed",
        "Vestigium.Brushes.Control.FillDisabled",
        "Vestigium.Brushes.Control.FillInput",
        "Vestigium.Brushes.Text.Primary",
        "Vestigium.Brushes.Text.Secondary",
        "Vestigium.Brushes.Text.Tertiary",
        "Vestigium.Brushes.Text.Disabled",
        "Vestigium.Brushes.Text.Inverse",
        "Vestigium.Brushes.Text.Heading",
        "Vestigium.Brushes.Text.OnSubtle",
        "Vestigium.Brushes.Text.Inactive",
        "Vestigium.Brushes.Text.Code",
        "Vestigium.Brushes.Text.Link",
        "Vestigium.Brushes.Accent.Primary",
        "Vestigium.Brushes.Accent.Hover",
        "Vestigium.Brushes.Accent.Pressed",
        "Vestigium.Brushes.Accent.Subtle",
        "Vestigium.Brushes.Accent.Softer",
        "Vestigium.Brushes.Selection.Fill",
        "Vestigium.Brushes.Selection.FillInactive",
        "Vestigium.Brushes.Selection.Text",
        "Vestigium.Brushes.Selection.Highlight",
        "Vestigium.Brushes.Selection.CellFocus",
        "Vestigium.Brushes.Stroke.Default",
        "Vestigium.Brushes.Stroke.Subtle",
        "Vestigium.Brushes.Stroke.Strong",
        "Vestigium.Brushes.Stroke.Focus",
        "Vestigium.Brushes.Stroke.Input",
        "Vestigium.Brushes.Stroke.Disabled",
        "Vestigium.Brushes.Status.Success",
        "Vestigium.Brushes.Status.SuccessHover",
        "Vestigium.Brushes.Status.SuccessPressed",
        "Vestigium.Brushes.Status.SuccessFill",
        "Vestigium.Brushes.Status.Warning",
        "Vestigium.Brushes.Status.WarningHover",
        "Vestigium.Brushes.Status.WarningPressed",
        "Vestigium.Brushes.Status.WarningFill",
        "Vestigium.Brushes.Status.Error",
        "Vestigium.Brushes.Status.ErrorHover",
        "Vestigium.Brushes.Status.ErrorPressed",
        "Vestigium.Brushes.Status.ErrorFill",
        "Vestigium.Brushes.Status.Info",
        "Vestigium.Brushes.Status.InfoFill",
        "Vestigium.Brushes.Status.Neutral",
        "Vestigium.Brushes.Status.NeutralFill",
        "Vestigium.Brushes.Grid.Line",
        "Vestigium.Brushes.Grid.AlternateRow",
        "Vestigium.Brushes.Grid.Header",
        "Vestigium.Brushes.Grid.RowHover",
        "Vestigium.Brushes.Scroll.Thumb",
        "Vestigium.Brushes.Scroll.ThumbHover",
        "Vestigium.Brushes.Scroll.ThumbDrag",
        "Vestigium.Brushes.Scroll.Track",
        "Vestigium.Brushes.Shadow",
        "Vestigium.Brushes.Terminal.Background",
        "Vestigium.Brushes.Terminal.Foreground",
        "Vestigium.Brushes.Terminal.Border",
        "Vestigium.Brushes.Terminal.BackgroundDisabled",
        "Vestigium.Brushes.Terminal.Comment",
        "Vestigium.Brushes.Terminal.Keyword",
        "Vestigium.Brushes.Terminal.String",
        "Vestigium.Brushes.Terminal.Number",
        "Vestigium.Brushes.Terminal.Error",
        "Vestigium.Brushes.Terminal.Cursor",
        "Vestigium.Brushes.Series.1",
        "Vestigium.Brushes.Series.2",
        "Vestigium.Brushes.Series.3",
        "Vestigium.Brushes.Series.4",
        "Vestigium.Brushes.Series.5",
        "Vestigium.Brushes.Series.6",
        "Vestigium.Brushes.Overlay.Scrim",
    ];
}
